name: movie_ditonton_2
description: Movie Ditonton App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  readmore: ^2.2.0
  test_cov_console: ^0.2.2
  flutter_bloc: ^8.1.1
  sqflite_sqlcipher: ^2.1.1+1

  core:
    path: core
  movie:
    path: movie
  tv:
    path: tv
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.8.12

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - certificates/